---
- hosts: repomirror6.massopen.cloud
  vars:
    repos:
      - rhel-6-server-rpms
      - rhel-6-server-eus-rpms
      - rhel-6-server-eus-optional-rpms
      - rhel-6-server-eus-rhn-tools-rpms
      - rhel-6-server-eus-supplementary-rpms
      - rhel-6-server-extras-rpms
    baseurl: http://repomirror6.massopen.cloud/repos/
    allowed_clients:
      - 140.247.115.0/24
      - 129.10.5.0/24
      - 71.248.161.49/32

  tasks:
    - name: ensure mirror root exists
      file:
        path: /srv/repos
        state: directory
        mode: 0755

    - name: set selinux context for mirror root
      sefcontext:
        target: '/srv/repos(/.*)?'
        setype: httpd_sys_content_t

    - name: enable repositories
      tags: [repos]
      rhsm_repository:
        name: '{{ item }}'
      loop: "{{ repos }}"

    - name: generate moc-rhel6.repo
      tags: [repofile]
      template:
        src: moc-rhel6.j2.repo
        dest: /srv/repos/moc-rhel6.repo

    - name: install packages
      tags: [packages]
      package:
        name: '{{ packages }}'
        state: present
      vars:
        packages:
          - ipset
          - yum-utils
          - httpd
          - createrepo

    - name: activate apache
      tags: [apache]
      service:
        name: httpd
        enabled: true
        state: started

    - name: install apache configuration
      tags: [apache]
      copy:
        src: repos.conf
        dest: /etc/httpd/conf.d/repos.conf
      notify: restart-httpd

    - name: install reposync cron job
      tags: [cron]
      copy:
        src: reposync-daily.sh
        dest: /etc/cron.daily/reposync-daily.sh
        mode: 0755

    - name: install repoclients ipset
      tags: [firewall]
      template:
        src: repoclients.j2.ipset
        dest: /etc/sysconfig/ipset
      notify: reload-ipset

    - name: install iptables ruleset
      tags: [firewall]
      copy:
        src: iptables
        dest: /etc/sysconfig/iptables
      notify: reload-iptables

  handlers:
    - name: restart-httpd
      command: >-
        apachectl -k restart

    - name: reload-ipset
      shell: |
        ipset flush repoclients
        ipset restore -! < /etc/sysconfig/ipset

    - name: reload-iptables
      command: >-
        service iptables reload
